version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: password

    # volumes:
    #   - ./data:/var/lib/mysql
  reviews:
    build: .
    depends_on:
      - db
    environment:
      WAIT_HOSTS: ‘db:3306’
    ports:
      - '3004:3004'




